version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chokurei
      POSTGRES_DB: medCloud
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgres://medcloud_user:chokurei@db:5433/medCloud
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  db-data:
